strats = {
    "generic": [
        "**Crabwalk** :crab: :crab: :crab:",
        "**TORNADO** :cloud_tornado:",
        "**Trickshots Only**: *Prior to every shot do a 360*",
        "**XRAY** :zap:: *Kill only through walls*",
        "**Glass-Cannon**: *Buy the most expensive weapon, no shields*",
        "**Sound Effects** :loud_sound:: *BOOM, POW, SPLAT, talk through all your actions*",
        "**Shout Casters** :loud_sound:: *Narrate every action until death*",
        "**Evasive Maneuvers**: Jump-peek every single corner",
        "**One Mic**: *Bottom of the leaderboard only can speak*",
        "**One at a time** :trophy:: Only one person can leave spawn at a time",
        "**Silent but deadly** :face_vomiting: :nauseated_face:: *Turn your volume down to 0*",
        "**Pistols Only** :gun:",
        "**Wild West** :cowboy:: *Buy a sheriff and can only speak in a western accent*",
        "**Follow the leader**: *Everyone has to follow the bottom ranked player in a line*",
        "**Is this CSGO** :nauseated_face:: *No abilities*",
        "**One clip wonder**: *No reloading, if you reload you must drop your weapon and pick up another*",
        "**Single You**: *No-one can press* **w**",
        "**Stuck in the mud** :poop:: *When a player gets a kill they must remain in place, until another player comes to take their place*",
        "**No crosshair**: *Turn your crosshair off*",
    ],
    "bind": [
        "Use teleporters 5 times as a team com**bin**e**d**",
        "Everyone on the team has to use at least 2 teleporters before you can plant / defuse spike",
    ],
    "haven": ["All C long cubby"],
    "icebox": ["All use A wire as the round starts"],
    "ascent": ["No doors: *No opening, closing OR breaking doors*"],
    "split": ["hide in ropes"],
    "fracture": ["zipline 5 times"],
    "breeze": ["all trapdoor"],
    "attack": [
        "Mr President :tie:",
        "The Fakeout: *Use ALL your util on one site, then attack another*",
    ],
    "defense": [
        "**Gambling** :dollar::dollar::dollar:: *All one site*",
        "**Personal Space**: *Can only purchase a shotgun*",
    ],
}
